######################################################################
# Automatically generated by qmake (2.01a) Tue May 27 15:09:28 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += data.h dmsclient.h logreader.h logsender.h mythread.h
SOURCES += dmsclient.cpp main.cpp mythread.cpp
